spring.application.name=question-api
server.port=80

api.version=v1
trivia.api.connectTimeout=30
trivia.api.readTimeout=30
trivia.api.writeTimeout=30
trivia.api.url=https://opentdb.com/api.php

parameter.default.amount=10

springdoc.swagger-ui.enabled=true
